src/Entity/Formation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Image;


/**
 * @ORM\Entity
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $titre;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="date")
     */
    private $begin_at;

// /**
// * @ORM\OneToOne(targetEntity="Image",cascade={"persist"})
// * @ORM\JoinColumn(nullable=false)
// */
// private $image;



    /**
     * @ORM\OneToMany(targetEntity=Participnt::class, mappedBy="Formation")
     */
    private $participnts;

    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="Formation")
     */
    private $participants;

    public function __construct()
    {
        $this->participnts = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    // Ajoutez ici les getters et setters pour chaque attribut

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;
        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getduree(): ?int
    {
        return $this->duree;
    }

    public function setduree(int $duree): self
    {
        $this->duree = $duree;
        return $this;
    }

    public function getBeginAt(): ?\DateTimeInterface
    {
        return $this->begin_at;
    }

    public function setBeginAt(\DateTimeInterface $begin_at): self
    {
        $this->begin_at = $begin_at;
        return $this;
    }

    // public function getImage(): ?string
    // {
    //     return $this->Image;
    // }

    // public function setImage(string $Image): self
    // {
    //     $this->Image = $Image;

    //     return $this;
    // }

    /**
     * @return Collection<int, Participnt>
     */
    public function getParticipnts(): Collection
    {
        return $this->participnts;
    }

    public function addParticipnt(Participnt $participnt): self
    {
        if (!$this->participnts->contains($participnt)) {
            $this->participnts[] = $participnt;
            $participnt->setFormation($this);
        }

        return $this;
    }

    public function removeParticipnt(Participnt $participnt): self
    {
        if ($this->participnts->removeElement($participnt)) {
            // set the owning side to null (unless already changed)
            if ($participnt->getFormation() === $this) {
                $participnt->setFormation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setFormation($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getFormation() === $this) {
                $participant->setFormation(null);
            }
        }

        return $this;
    }

    // public function getImage(): ?Image
    // {
    //     return $this->image;
    // }

    // public function setImage(Image $image): self
    // {
    //     $this->image = $image;

    //     return $this;
    // }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('price')
            ->add('duree')
            ->add('begin_at')
            ->add('image', FileType::class, [
                'label' => 'Image',
                'required' => false, 
                'attr' => ['class' => 'form-control-file']
            ])
            ->add('Valider', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Entity\Image;
use App\Entity\Participant;
use phpDocumentor\Reflection\PseudoTypes\True_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;



use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use App\Form\FormationType;
use Symfony\Component\Form\Extension\Core\DataTransformer\FileToStringTransformer;

use Symfony\Component\Form\FormBuilderInterface;






class FormationController extends AbstractController
{
    /**
     * @Route("/formation", name="app_formation")
     */
    // public function index(): Response
    // {
    //     return $this->render('formation/index.html.twig', [
    //         'controller_name' => 'FormationController',
    //     ]);
    // }

    /* *
    *Route('/formation', name: 'app_formation')
    **/
    public function index(): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $Formation = new Formation();
        $Formation->setTitre("formation mern ");
        $Formation->setduree("30");
        $Formation->setPrice("2.00");
        $Formation->setBeginAt(new \DateTimeImmutable());
        // Assuming you have already instantiated the $Formation object

        // $image = new Image();
        // $image->setUrl("https://i.ytimg.com/vi/dapS3HkX3Wc/maxresdefault.jpg");
        // $image->setAlt("formation");


        //Ajout de PArticipant 
        $Participant1 = new Participant();
        $Participant1->setEmail("belgacem@example.com");
        $Participant1->setFonction("Fonction1");
        $Participant1->setIsSubscribe(true);
        $Participant1->setNom("belgacem");

        $Participant2 = new Participant();
        $Participant2->setEmail("belgacem@example.com");
        $Participant2->setFonction("Fonction2");
        $Participant2->setIsSubscribe(true);
        $Participant2->setNom("belgacem");
        $entityManager->persist($Formation);
        $entityManager->persist($Participant2);
        $entityManager->persist($Participant1);
        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();
        return $this->render('formation/index.html.twig', [
            'formation' => $Formation,
        ]);
    }
    /**
     * @Route("/formation/{id}", name="Formation_show")
     */
    public function show($id, Request $request)
    {
        $formation = $this->getDoctrine()
            ->getRepository(Formation::class)
            ->find($id);
        $em = $this->getDoctrine()->getManager();
        $lesformations = $em->getRepository(Formation::class)
            ->findBy(['id' => $id]);
        $publicPath = $request->getScheme() . '://' . $request->getHttpHost() . $request->getBasePath() . '/uploads/Formations/';
        if (!$formation) {
            throw $this->createNotFoundException(
                'No Formation found for id ' . $id
            );
        }
        return $this->render('formation/show.html.twig', [
            'lesformations' => $lesformations,
            'formation' => $formation,
            'publicPath' => $publicPath
        ]);
    }

    /**
     * @Route("/", name="home")
     */


    public function home(Request $request)
    {
        // Create the search form
        $form = $this->createFormBuilder()
            ->add('critere', TextType::class)
            ->add('valider', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();
        $repo = $entityManager->getRepository(Formation::class);

        // Fetch all formations
        $lesFormations = $repo->findAll();

        // Perform search when the form is submitted
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $critere = $data['critere']; // Retrieve the value of 'critere' field
            $lesFormations = $repo->findBy(['titre' => $critere]);
        }

        return $this->render(
            'formation/home.html.twig',
            ['lesformations' => $lesFormations, 'form' => $form->createView()]
        );
    }





    /**
     * @Route("/Ajouter", name="Ajouter")
     */

    public function ajouter(Request $request)
    {
        $formation = new Formation();

        $form = $this->createFormBuilder($formation)
            ->add('titre', TextType::class)
            ->add('begin_at', DateType::class)
            ->add('price', NumberType::class)
            ->add('duree', IntegerType::class)
            // ->add('Image', FileType::class)
            ->add('Valider', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($formation);
            $em->flush();

            // Redirection vers la page d'accueil
            return new RedirectResponse($this->generateUrl('home'));
        }

        return $this->render(
            'formation/ajouter.html.twig',
            ['form' => $form->createView()]
        );
    }


    //     /**
    //  * @Route("/Ajouter_formation", name="Ajouter_job")
    //  */
    // public function ajouter2(Request $request)
    // {
    //     $publicPath = "uploads/Formation/";
    //     $formation = new Formation();
    //     $form = $this->createForm(FormationType::class, $formation);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $image = $form->get('image')->getData();
    //         if ($image) {
    //             $imageName = $formation->getTitre() . '.' . $image->guessExtension();
    //             $image->move($publicPath, $imageName);
    //             $formation->setImage($imageName);
    //         }

    //         $em = $this->getDoctrine()->getManager();
    //         $em->persist($formation);
    //         $em->flush();

    //         return $this->redirectToRoute('home');
    //     }

    //     return $this->render(
    //         'formation/ajouter.html.twig',
    //         ['form' => $form->createView()]
    //     );
    // }


    /**
     * @Route("formation/supp/{id}", name="formation_delete")
     */
    public function delete($id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $formation = $entityManager->getRepository(Formation::class)->find($id);

        if (!$formation) {
            throw $this->createNotFoundException('No formation found for this id: ' . $id);
        }

        $participants = $formation->getParticipants();

        foreach ($participants as $participant) {
            $entityManager->remove($participant);
        }

        $entityManager->remove($formation);
        $entityManager->flush();

        return $this->redirectToRoute('home');
    }


    /**
     * @Route("/editF/{id}", name="edit_formation")
     * Method({"GET","POST"})
     */
    public function edit(Request $request, $id)
    {
        $formation = $this->getDoctrine()
            ->getRepository(Formation::class)
            ->find($id);

        if (!$formation) {
            throw $this->createNotFoundException(
                'No formation found for id ' . $id
            );
        }

        $form = $this->createFormBuilder($formation)
            ->add('titre', TextType::class)
            ->add('price', MoneyType::class)
            ->add('duree', IntegerType::class)
            ->add('begin_at', DateType::class)
            // ->add('Image', FileType::class, [
            //     'required' => false,
            //     'data_class' => null,
            // ])
            ->add('save', SubmitType::class, ['label' => 'Update Formation'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            return $this->redirectToRoute('home', ['id' => $formation->getId()]);
        }

        return $this->render('formation/ajouter.html.twig', [
            'form' => $form->createView(),
            'formation' => $formation,
        ]);
    }




    /**
     * @Route("/listeformation", name="liste_formation")
     */
    public function afficherList(Request $request)
    {
        $form = $this->createFormBuilder()
            ->add('critere', TextType::class)
            ->add('valider', SubmitType::class)
            ->getForm();
        $form->handleRequest($request);

        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Formation::class);
        $lesFormations = $repo->findAll();
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $critere = $data['critere']; // Retrieve the value of 'critere' field
            $lesFormations = $repo->findBy(['titre' => $critere]);
        }



        return $this->render('formation/liste.html.twig', [
            'lesFormations' => $lesFormations,
            'form' => $form->createView()
        ]);
    }
}

templates/formation/ajouter.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter Formation{% endblock %}

{% block body %}
    <div class="container">
    <h2>Ajouter une formation</h2>
    <div class="card">
        <div class="card-body">
            {{ form_start(form, {'attr': {'class': 'form'}}) }}
            <div class="form-group">
                {{ form_label(form.titre) }}
                {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.price) }}
                {{ form_widget(form.price, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.duree) }}
                {{ form_widget(form.duree, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.begin_at) }}
                {{ form_widget(form.begin_at, {'attr': {'class': 'form-control'}}) }}
            </div>
           
            {{ form_end(form) }}
        </div>
    </div>
</div>


                  
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/formation/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  {{ form_start(form) }}
  {{ form_widget(form) }}
  {{ form_end(form) }}

  <table class="table table-hover table-striped m-10 p-10" border="1">
    <thead>
      <tr>
        <th>
          ID
        </th>
        <th>
          Titre
        </th>
        <th>
          Prix
        </th>
        <th>
          Durée
        </th>
        <th>
          Date de début
        </th>
        {# <th>
          Image
        </th> #}
        <th>
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
      {% for formation in lesformations %}
        <tr>
          <td>
            {{ formation.id }}
          </td>
          <td>
            {{ formation.titre }}
          </td>
          <td>
            {{ formation.price }}
          </td>
          <td>
            {{ formation.duree }}
          </td>
          <td>
            {{ formation.beginAt|date('d-m-Y') }}
          </td>
          {# <td>
            <img src="{{ asset(formation.image) }}" />
          </td> #}

          <td>
            <a class="btn btn-primary" href="{{ path('Ajouter') }}">Ajouter</a>
            <a class="btn btn-danger"
              href="{{
              path(
                'formation_delete',
                {
                  id: formation.id
                }
              )
              }}"
              onclick="return confirm('Are you sure you want to delete {{
              formation.titre
              }}')">
              Supprimer
            </a>
            <a class="btn btn-warning"
              href="{{
              path(
                'edit_formation',
                {
                  id: formation.id
                }
              )
              }}">
              Modifier
            </a>
            <a class="btn btn-info"
              href="{{
              path(
                'Formation_show',
                {
                  id: formation.id
                }
              )
              }}">
              Voir
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FormationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Formation Ajouté avec succès {{ formation.titre }}! ✅</h1>
</div>
{% endblock %}

templates/formation/liste.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="container">
    <h2>
      Liste des formations <small><a href="{{ path('Ajouter') }}"
          class="btn btn-primary">
          Ajouter
        </a></small>
    </h2>
  </div>
  {% for msg in app.flashes('notice') %}
    <div class="alert alert-info">
      {{ msg }}
    </div>
  {% endfor %}

  {{ form_start(form) }}
  {{ form_widget(form) }}
  {{ form_end(form) }}

  <table class="table table-hover table-striped w-100 h-100 m-5 p-5" border="1">
    <thead>
      <tr>
        <th>
          ID
        </th>
        <th>
          Titre
        </th>
        <th>
          Prix
        </th>
        <th>
          Durée
        </th>
        <th>
          Date de début
        </th>
        {# <th>
          Image
        </th> #}
        <th>
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
      {% for formation in lesFormations %}
        <tr>
          <td>
            {{ formation.id }}
          </td>
          <td>
            {{ formation.titre }}
          </td>
          <td>
            {{ formation.price }}
          </td>
          <td>
            {{ formation.duree }}
          </td>
          <td>
            {{ formation.beginAt|date('d-m-Y') }}
          </td>
          {# <td>
            <img src="{{ asset(formation.image) }}" />
          </td> #}
          <td>
            <a class="btn btn-primary" href="{{ path('Ajouter') }}">Ajouter</a>
            <a class="btn btn-danger"
              href="{{
              path(
                'formation_delete',
                {
                  id: formation.id
                }
              )
              }}"
              onclick="return confirm('Are you sure you want to delete {{
              formation.titre
              }}')">
              Supprimer
            </a>
            <a class="btn btn-warning"
              href="{{
              path(
                'edit_formation',
                {
                  id: formation.id
                }
              )
              }}">
              Modifier
            </a>
            <a class="btn btn-info"
              href="{{
              path(
                'Formation_show',
                {
                  id: formation.id
                }
              )
              }}">
              Voir
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
<div class="text-center">
  <a href="{{ path('home') }}" class="btn btn-primary">Retour à la page d'accueil</a>
</div>

{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ parent() }} - Edit
{% endblock %}

{% block titre %}
  {{ parent()|upper }} - Consultation de {{ formation.titre }}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h1 class="mb-4">
                        Titre: {{ formation.titre }}
                    </h1>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table">
                                <tr>
                                    <th>Durée:</th>
                                    <td>{{ formation.duree }}</td>
                                </tr>
                                <tr>
                                    <th>Date de début:</th>
                                    <td>{{ formation.beginAt|date('d-m-Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Prix:</th>
                                    <td>{{ formation.price }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-6 offset-md-3 text-center">
            <a href="{{ path('home') }}" class="btn btn-primary">
                Retour à la page Accueil
            </a>
        </div>
    </div>
</div>

{% endblock %}

templates/formation/update.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter Formation{% endblock %}

{% block body %}
    <div class="container">
        <h2>Ajouter une formation</h2>
        <div class="card">
            <div class="card-body">
                {{ form_start(form, {'attr': {'class': 'form'}}) }}
                    <div class="form-group">
                        {{ form_label(form.titre) }}
                        {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.price) }}
                        {{ form_widget(form.price, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.duree) }}
                        {{ form_widget(form.duree, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.begin_at) }}
                        {{ form_widget(form.begin_at, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
    {{ form_label(form.image) }}
    {{ form_widget(form.image, {'attr': {'class': 'form-control-file'}}) }}
</div>

                  
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}